import type { Metadata } from "next"
import Script from "next/script"
import { Inter } from "next/font/google"

import "./globals.css"

import CustomProvider from "./provider"
import CsrfTokenProvider from "@/components/utils/csrfTokenProvider"
import NavBar from "@/components/commons/navBar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout(
  { children, }
    : Readonly<{ children: React.ReactNode; }>
) {

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <CustomProvider>
          <CsrfTokenProvider />
          <div className="h-screen bg-gray-200">
            <NavBar />
            <div className="bg-gray-200">
              {children}
            </div>
          </div>
        </CustomProvider>
      </body>
    </html>
  )
}
